### ISSUE TITLE
Keep connection alive with JDBCRecordReader?

### ISSUE THREAD

**Issue by bqchristie** [EasyBatch/easybatch-framework#129] opened 2015-10-02 15:51 UTC
When I run a job on a schedule the second time it runs the connection is closed.  It looks like JDBCRecordReader closes the connection in the close() method.   When running as a scheduled job is there a way to keep the connection open? 

Great framework btw....

**Comment by benas** [comment] 2015-10-02 20:00
Hi @bqchristie ,

Thank you for pointing out this issue! I was able to reproduce it (with other database readers as well: jpa, hibernate and mongodb).

The engine automatically closes the reader at the end of the job (to prevent resource leak).

We can add a parameter to not close the reader (like in the [JdbcTransactionJobListener](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-jdbc/src/main/java/org/easybatch/jdbc/JdbcTransactionJobListener.java#L64)). I think of:

```java
Engine engine = aNewEngine()
   .reader(new JdbcRecordReader(connection, query))
   .closeReader(false)
   .build();

// or

Engine engine = aNewEngine()
   .reader(new JdbcRecordReader(connection, query), false) // overloaded, default to true
   .build();
```

The `closeReader(false)` will prevent the engine from closing the reader, hence, it will be reusable in a scheduled job. What do you think?

The only problem with this solution is that the connection can be alive indefinitely (imagine scheduling several jobs once per day) which may cause a resource leak.. But we can warn about that in the documentation so the user is aware of it.

> Great framework btw....

Many thanks! Glad you like it :-)

Regards
Mahmoud

**Comment by bqchristie** [comment] 2015-10-02 20:22
Hey Mahmoud - thanks for getting back to me I appeciate it.

I like your solution.   Your code is much nicer than what I tend to write so I defer to your judgement.

I see your point about leaving the open connections.   For my purposes a warning would be enough but it is a valid concern.

For what it's worth this is what I did to get it up an running...

Added property...

	private boolean keepAlive; 
 
Added constructor...

	public JdbcRecordReader(final Connection connection, final String query, final boolean keepAlive) {
       this(connection, query);
       this.keepAlive = keepAlive;
    }
   
 
Modified close...

	public void close() throws RecordReaderClosingException {
	....
            if (connection != null && !this.keepAlive) {
                connection.close();
            }
     ....
	}
	
Cheers,
Bruce

**Comment by benas** [comment] 2015-10-02 21:19
Your solution is also a nice one :+1: but we need to add a keepAlive flag, add a constructor and implement the logic in the close method in all database readers (Since the issue is the same for all). Which is not the case if we make it configurable at the engine level.

Another solution is also to:
* pass a `DriverManager` to the `JdbcRecordReader` instead of `Connection`, and create new connections in the `open` method
* pass a `EntityManagerFactory` to the `JpaRecordReader` instead of `EntityManager`, and create new entity managers in the `open` method
* Etc,

But I don't like it very much from an API design point of view.

I just deployed a new 3.1.1-SNAPSHOT version to maven's central repo which overloads the `reader` method in the `EngineBuilder` with a new `keepAlive` flag:

```java
Engine engine = aNewEngine()
   .reader(new JdbcRecordReader(connection, query), true) // keepAlive = true
   .build();
```

This will keep the reader alive and should be reusable in a scheduled job. You can give it a try and tell me what you think. I'll plan this addition to the next release. Keep tuned.

**Comment by bqchristie** [comment] 2015-10-06 00:05
Great solution.  Thanks!

**Closed** 2015-10-06 20:20 UTC
Labels: enhancement, feature
